### ISSUE TITLE
Question 01=> C Programming Language 

### ISSUE THREAD

**Issue by dipu-s-repo68** [dipu-s-repo68/hacktoberfest2024-third.github.io#1]
Question: Write a C function that swaps two integers without using a temporary variable, arithmetic operators, or bitwise operators. You are only allowed to manipulate the values using pointer operations and memory addresses.

**Comment by alpharsh** [comment]
I'm interested in this please assign this to me

**Comment by dipu-s-repo68** [comment]
@alpharsh done

**Comment by guptushar27** [comment]
please assign this to me

**Comment by dipu-s-repo68** [comment]
@guptushar27 if you complete it then I'll assign you and merge your PR

**Comment by guptushar27** [comment]
ok I will complete it

**Comment by alpharsh** [comment]
i"ve already completed
