### ISSUE TITLE
Question 02 => C Programming  Language

### ISSUE THREAD

**Issue by dipu-s-repo68** [dipu-s-repo68/hacktoberfest2024-third.github.io#2]
### Project 
Create a program for making Calculator in C language

> Please don't make it as a basic one

**Comment by SnehaghoshBarsha444** [comment]
@dipu-s-repo68 sir,
I'm eager to do it
Can you assign me ?

**Comment by dipu-s-repo68** [comment]
@SnehaghoshBarsha444 done
